import { TopBar } from "@/components/top-bar"
import { SiteFooter } from "@/components/site-footer"
import Link from "next/link"
import { FileText, ArrowLeft } from "lucide-react"

export default function TermsOfServicePage() {
  const currentDate = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })

  return (
    <div className="min-h-screen bg-black text-white">
      <TopBar />

      <div className="max-w-4xl mx-auto px-4 py-16">
        <div className="mb-8">
          <Link
            href="/"
            className="inline-flex items-center text-gray-400 hover:text-fram3-yellow transition-colors mb-6"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            <span>Back to Home</span>
          </Link>

          <div className="flex items-center mb-4">
            <FileText className="h-6 w-6 text-fram3-yellow mr-3" />
            <h1 className="text-3xl font-bold">Terms and Conditions</h1>
          </div>
          <p className="text-sm text-gray-400">Last Updated: {currentDate}</p>
        </div>

        <div className="prose prose-invert prose-yellow max-w-none">
          <p className="text-gray-300">
            Welcome to Fram3 ("we," "our," or "us"). These Terms and Conditions (the "Terms") govern your access to and
            use of our website, platform, and related services (collectively, the "Services"). By accessing or using the
            Services, you agree to be bound by these Terms and our Privacy Policy. If you do not agree, you must
            discontinue using the Services immediately.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">1. Acceptance of Terms</h2>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>
              <span className="font-medium">1.1. Binding Agreement.</span> By creating an account, clicking "I Agree,"
              or using any part of our Services, you acknowledge and agree that these Terms form a legally binding
              agreement between you and Fram3.
            </li>
            <li>
              <span className="font-medium">1.2. Modifications.</span> We reserve the right to amend these Terms at any
              time. We will notify you of any significant changes by posting an updated version on our website or
              contacting you directly. Your continued use of the Services after the effective date of any changes
              constitutes your acceptance of those changes.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">2. Eligibility & Account Registration</h2>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>
              <span className="font-medium">2.1. Eligibility.</span> You must be at least the age of majority in your
              jurisdiction (or have parental consent if legally permissible) and capable of entering into a binding
              contract to use the Services.
            </li>
            <li>
              <span className="font-medium">2.2. Account Creation.</span> You may need to create an account to access
              certain features. You agree to provide accurate, current, and complete information and to update such
              information if it changes.
            </li>
            <li>
              <span className="font-medium">2.3. Account Security.</span> You are responsible for maintaining the
              confidentiality of your login credentials and for all activities that occur under your account.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">3. Description of Services</h2>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>
              <span className="font-medium">3.1. Platform Purpose.</span> Fram3 offers AI-powered video generation,
              script analysis, and related creative services (the "Platform"). The Platform allows users to transform
              ideas, scripts, and other content into videos optimized for audience engagement.
            </li>
            <li>
              <span className="font-medium">3.2. No Guarantee of Results.</span> Fram3 does not guarantee that the
              Services will meet your expectations or achieve specific results. Any reliance on suggestions or outputs
              generated by our AI (e.g., AVIA) is at your own risk.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">4. User Content</h2>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>
              <span className="font-medium">4.1. Definition.</span> "User Content" refers to any text, scripts, images,
              videos, or other media uploaded, submitted, generated, or otherwise provided by you through the Services.
            </li>
            <li>
              <span className="font-medium">4.2. Ownership.</span> You retain full ownership of any intellectual
              property rights that you hold in your User Content. Fram3 does not claim any ownership in your User
              Content.
            </li>
            <li>
              <span className="font-medium">4.3. Responsibility & Legal Compliance.</span> You are solely responsible
              for the originality, legality, and appropriateness of your User Content. You warrant that you have all
              necessary rights and permissions to submit your User Content and that it does not violate any third-party
              rights or applicable laws.
            </li>
            <li>
              <span className="font-medium">4.4. Liability for Stolen or Forged Scripts.</span> Fram3 is not responsible
              for verifying the authenticity of any User Content. Fram3 will not be liable for any losses, claims, or
              damages resulting from stolen, forged, or otherwise infringing scripts or materials.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">5. License to Fram3</h2>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>
              <span className="font-medium">5.1. Limited License.</span> By submitting User Content, you grant Fram3 and
              its affiliates a non-exclusive, worldwide, royalty-free, transferable license to host, store, process,
              transmit, and display your User Content solely for the purpose of providing the Services to you.
            </li>
            <li>
              <span className="font-medium">5.2. Optional AI Model Training</span>
              <ul className="list-disc pl-5 space-y-2 mt-2">
                <li>
                  <span className="font-medium">Opt-In.</span> Your User Content will be used to train and improve our
                  AI models only if you explicitly opt in.
                </li>
                <li>
                  <span className="font-medium">Licensed Training Benefits & Royalties.</span> If you opt in to license
                  your content for training, you may receive enhanced features and potential royalties or other benefits
                  if other users generate derivative works through AI models enriched by your licensed data. Any such
                  arrangement will be governed by a separate agreement.
                </li>
                <li>
                  <span className="font-medium">Synthetic Data Generation.</span> We may generate or use synthetic data
                  as part of our ongoing efforts to refine our models without compromising your personal or proprietary
                  information.
                </li>
              </ul>
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">6. Prohibited Activities</h2>
          <p className="text-gray-300">You agree not to:</p>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>
              Use the Services for any unlawful purpose or in violation of any applicable local, state, national, or
              international law.
            </li>
            <li>Upload or transmit any content that is defamatory, infringing, obscene, or otherwise objectionable.</li>
            <li>
              Interfere with the proper working of the Services, including bypassing or circumventing security features.
            </li>
            <li>
              Reverse-engineer or otherwise attempt to extract source code or algorithms from the Platform, except as
              permitted by law.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">7. Subscriptions, Fees & Payments</h2>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>
              <span className="font-medium">7.1. Pricing Plans.</span> Various subscription tiers may be available for
              the Services. Each plan specifies its own features, pricing, and usage limits, which are subject to
              change.
            </li>
            <li>
              <span className="font-medium">7.2. Billing Cycle.</span> If you elect to purchase a subscription, you
              authorize Fram3 (or our third-party payment processor) to charge the applicable fees to your payment
              method on a recurring basis until you cancel the subscription.
            </li>
            <li>
              <span className="font-medium">7.3. Refund Policy.</span> We may offer a 30-day money-back guarantee or
              other refunds per the plan details. Please review the specific plan for refund eligibility.
            </li>
            <li>
              <span className="font-medium">7.4. Changes to Pricing.</span> We reserve the right to adjust pricing or
              introduce new fees with reasonable notice to you. Your continued use of the Services after such notice
              constitutes acceptance of any new or modified fees.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">8. Intellectual Property & Ownership</h2>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>
              <span className="font-medium">8.1. Fram3 IP.</span> All trademarks, logos, trade dress, service marks,
              patents, copyrights, and other proprietary rights associated with the Services remain the sole property of
              Fram3 or its licensors.
            </li>
            <li>
              <span className="font-medium">8.2. Restrictions.</span> Except as expressly permitted in these Terms, you
              may not copy, modify, distribute, sell, or lease any part of our Services or included software.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">9. Disclaimer of Warranties</h2>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>
              <span className="font-medium">9.1. As-Is.</span> The Services are provided on an "AS IS" and "AS
              AVAILABLE" basis without warranties of any kind, whether express, implied, or statutory.
            </li>
            <li>
              <span className="font-medium">9.2. No Endorsement.</span> Fram3 does not endorse or take responsibility
              for any User Content.
            </li>
            <li>
              <span className="font-medium">9.3. No Guarantees.</span> We do not guarantee the completeness, accuracy,
              or reliability of the outputs generated by our AI models or any decisions you make based on them.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">10. Limitation of Liability</h2>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>
              <span className="font-medium">10.1. Exclusion of Indirect Damages.</span> To the fullest extent permitted
              by law, Fram3 shall not be liable for any indirect, incidental, consequential, or punitive damages arising
              out of or related to your use of the Services.
            </li>
            <li>
              <span className="font-medium">10.2. Aggregate Liability.</span> In no event shall Fram3's total liability
              exceed the amount you have paid to Fram3 in the 12 months preceding the event giving rise to the claim.
            </li>
            <li>
              <span className="font-medium">10.3. User Content Issues.</span> Fram3 shall have no liability for any
              stolen or forged scripts or any claims arising from the infringement or misuse of User Content by you or
              any third party.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">11. Indemnification</h2>
          <p className="text-gray-300">
            You agree to defend, indemnify, and hold harmless Fram3, its affiliates, officers, agents, and employees
            from any claims, liabilities, damages, losses, and expenses (including reasonable attorneys' fees) arising
            out of or related to:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>Your User Content, including any claims that it infringes on third-party rights.</li>
            <li>Your breach of these Terms.</li>
            <li>Your violation of any law or the rights of a third party.</li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">12. Termination</h2>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>
              <span className="font-medium">12.1. User-Initiated Termination.</span> You may deactivate your account or
              discontinue use of the Services at any time. If you cancel a paid subscription, you may continue to have
              access to the Services until the end of your current billing period.
            </li>
            <li>
              <span className="font-medium">12.2. Fram3's Right to Terminate.</span> We reserve the right to suspend or
              terminate your account or access to the Services at any time, with or without notice, for any breach of
              these Terms or if required by law.
            </li>
            <li>
              <span className="font-medium">12.3. Survival.</span> Upon termination of these Terms, any provisions that
              by their nature should survive termination (e.g., indemnities, disclaimers, limitations of liability, and
              any licenses that extend beyond termination) shall remain in effect.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">13. Governing Law & Dispute Resolution</h2>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>
              <span className="font-medium">13.1. Governing Law.</span> These Terms shall be governed by and construed
              in accordance with the laws of India, without regard to its conflict of law provisions.
            </li>
            <li>
              <span className="font-medium">13.2. Dispute Resolution.</span> Any disputes arising from or related to
              these Terms shall be resolved through binding arbitration in Bangalore, India unless otherwise required by
              law.
            </li>
            <li>
              <span className="font-medium">13.3. Class Action Waiver.</span> You agree to resolve any disputes on an
              individual basis and waive the right to participate in a class action lawsuit or class-wide arbitration.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">14. International Use</h2>
          <p className="text-gray-300">
            You agree to comply with all applicable laws regarding online conduct and acceptable content in your
            jurisdiction. You also agree to comply with all applicable export controls, including restrictions on
            destinations, end users, and end use.
          </p>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">15. Miscellaneous</h2>
          <ul className="list-disc pl-5 space-y-2 text-gray-300">
            <li>
              <span className="font-medium">15.1. Entire Agreement.</span> These Terms, along with the Privacy Policy
              and any additional terms you agree to when using specific Services, constitute the entire agreement
              between you and Fram3.
            </li>
            <li>
              <span className="font-medium">15.2. Severability.</span> If any provision is held invalid or
              unenforceable, the remaining provisions shall remain in full force and effect.
            </li>
            <li>
              <span className="font-medium">15.3. No Waiver.</span> Failure by Fram3 to enforce any right or provision
              of these Terms shall not constitute a waiver of such right or provision.
            </li>
            <li>
              <span className="font-medium">15.4. Assignment.</span> You may not assign or transfer these Terms without
              our prior written consent. Fram3 may assign or transfer these Terms, at its sole discretion, without
              restriction.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">16. Contact Us</h2>
          <p className="text-gray-300">
            If you have any questions or concerns about these Terms or the Services, please contact us:
          </p>
          <ul className="list-none pl-5 space-y-1 text-gray-300">
            <li>
              <span className="font-medium">Email:</span> support@fram3.ai
            </li>
            <li>
              <span className="font-medium">Address:</span> #1035, 3rd Floor, Vijaya Bank layout, Bilekahalli, Bangalore
              - 560076
            </li>
            <li>
              <span className="font-medium">Telephone:</span> +91 94489 08617
            </li>
          </ul>
          <p className="text-sm italic mt-4 text-gray-400">Effective Date: {currentDate}</p>
          <p className="text-sm text-gray-300">
            By using the Fram3 platform, you acknowledge that you have read, understood, and agree to be bound by these
            Terms.
          </p>
        </div>
      </div>
      <SiteFooter />
    </div>
  )
}

